# Generated by Django 5.2.5 on 2025-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0003_fix_token_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
