# Generated by Django 5.2 on 2025-07-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0001_initial_squashed_0003_merge_20250724_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='full_name',
            new_name='license_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivo.ride'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivo.ride'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivo.driverprofile'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='trip_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
