# Generated by Django 5.2.5 on 2025-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
