# Generated by Django 5.2 on 2025-07-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0002_alter_clientprofile_phone_number_and_more'),
        ('drivo', '0002_ride_review_payment'),
    ]

    operations = [
    ]
