# Generated by Django 5.2.5 on 2025-08-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0002_alter_ride_dropoff_latitude_and_more'),
    ]

    operations = [
    ]
