# Generated by Django 5.2.5 on 2025-08-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0003_clientprofile_destination_clientprofile_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='source',
        ),
    ]
