# Generated by Django 5.2.5 on 2025-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
