# Generated by Django 5.2.5 on 2025-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0005_remove_user_username_driverprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
