# Generated by Django 5.2.5 on 2025-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0006_remove_driverprofile_is_approved_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
