# Generated by Django 5.2.5 on 2025-08-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0007_user_cnic_user_is_logged_in_user_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
    ]
