# Generated by Django 5.2.5 on 2025-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0009_emailotp_is_used_alter_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
