# Generated by Django 5.2.5 on 2025-08-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivo', '0010_clientprofile_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
