/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LiveLocation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EnterEmail` | `/EnterEmail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/GrantLocation` | `/GrantLocation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LiveLocation` | `/LiveLocation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NewPassword` | `/NewPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/OTP` | `/OTP`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TypeSelector` | `/TypeSelector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Client/Profile` | `/Client/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Driver/Profile` | `/Driver/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/LiveLocation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/EnterEmail` | `/EnterEmail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/GrantLocation` | `/GrantLocation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LiveLocation` | `/LiveLocation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/NewPassword` | `/NewPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/OTP` | `/OTP`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Signup` | `/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TypeSelector` | `/TypeSelector`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Client/Profile` | `/Client/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Driver/Profile` | `/Driver/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/LiveLocation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/EnterEmail${`?${string}` | `#${string}` | ''}` | `/EnterEmail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/GrantLocation${`?${string}` | `#${string}` | ''}` | `/GrantLocation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LiveLocation${`?${string}` | `#${string}` | ''}` | `/LiveLocation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/NewPassword${`?${string}` | `#${string}` | ''}` | `/NewPassword${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/OTP${`?${string}` | `#${string}` | ''}` | `/OTP${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Signup${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TypeSelector${`?${string}` | `#${string}` | ''}` | `/TypeSelector${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Client/Profile${`?${string}` | `#${string}` | ''}` | `/Client/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Driver/Profile${`?${string}` | `#${string}` | ''}` | `/Driver/Profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LiveLocation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EnterEmail` | `/EnterEmail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/GrantLocation` | `/GrantLocation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LiveLocation` | `/LiveLocation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NewPassword` | `/NewPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/OTP` | `/OTP`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TypeSelector` | `/TypeSelector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Client/Profile` | `/Client/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Driver/Profile` | `/Driver/Profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
